import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./(components)/Navbar";
import { ThemeProvider } from "./(components)/ThemeProvider";
import AppWrapper from "./(components)/AppWrapper";
import ChatbotFab from "./(components)/ChatbotFab";

const outfit = Outfit({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "|Kaustubh Pathak|",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={outfit.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <AppWrapper>
            <Navbar/>
            {children}
            <ChatbotFab />
          </AppWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
